[package]
name = "queue"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.29.2", features = ["aio", "tokio-comp"] }
tokio = { version = "1.44.1", features = ["macros", "rt", "sync", "time"] }
uuid = { version = "1.16.0", features = ["v7"] }
